services:
  - type: web
    name: market-link
    env: ruby
    plan: free
    numInstances: 1
    buildCommand: bin/render-build.sh
    startCommand: bundle exec puma -C config/deploy/puma.rb
    envVars:
      - key: DATABASE_URL
        value: "postgresql://rails_valid_db_owner:npg_wAXcumgqC69E@ep-sparkling-heart-a4rl690e-pooler.us-east-1.aws.neon.tech/rails_valid_db?sslmode=require"
      - key: RAILS_MASTER_KEY
        sync: false