services:
  - type: web
    name: market-link
    env: ruby
    plan: free
    numInstances: 1
    buildCommand: bin/render-build.sh
    startCommand: bundle exec puma -C config/deploy/puma.rb
    envVars:
      - key: DATABASE_URL
        value: "postgresql://talaeris_db_owner:npg_2umngz9MRtPW@ep-bitter-sunset-a412g3hx-pooler.us-east-1.aws.neon.tech/talaeris_db?sslmode=require"
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SOLID_QUEUE_IN_PUMA
        value: "true"