services:
  - type: web
    name: market-link
    env: ruby
    plan: free
    numInstances: 1
    buildCommand: bin/render-build.sh
    startCommand: bundle exec puma -C config/deploy/puma.rb
    envVars:
      - key: DATABASE_URL
        value: "postgresql://rails_test_db_owner:npg_LZhwUICoF36X@ep-weathered-art-a4valqwi-pooler.us-east-1.aws.neon.tech/rails_test_db?sslmode=require"
      - key: RAILS_MASTER_KEY
        sync: false